version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  server-build-and-test:
    executor:
      name: node/default
    steps:
      - checkout     
      - run:
          command: npm install
          working_directory: ./server
      - run:
          name: Running server tests      
          command: npm test
          working_directory: ./server        
  client-build-and-test:
    executor:
      name: node/default
    steps:
      - checkout     
      - run:
          command: npm install
          working_directory: ./client
      - run:
          name: Running client tests      
          command: npm test
          working_directory: ./client    
  publish-docker:
    machine: true
    steps:          
      - checkout
      - run:
          name: Docker publish server
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t wtycjan/node-react-cicd-server:$TAG .
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push wtycjan/node-react-cicd-server:$TAG
          working_directory: ./server
workflows:
    build-and-test:
      jobs:
        - server-build-and-test:
          filters:
            branches:
              only:
                - master
        - client-build-and-test:
          filters:
            branches:
              only:
                - master
        - publish-docker:
            requires:
              - server-build-and-test
              - client-build-and-test
